Repository dalbitresb12/minigit, pull requests merged in 2021-06, with the labels that each got.

#2 Fix windows build workflow
  .github/workflows/cmake.yml
  CMakeLists.txt
Labels: chore

#1 Added File classes
  CMakeLists.txt
  document.hpp
  file.hpp
  folder.hpp
Labels: feature

#3 Fixed Constructor File Classes
  document.hpp
  file.hpp
  folder.hpp
Labels: bug

#4 Feat/Add data structures
  AVL.hpp
  HashTables.hpp
Labels: feature

#7 Changed vcpkg URL from SSH to HTTPS
  .gitmodules
Labels: bug

#6 Moved files to src folder and updated CMakeLists
  CMakeLists.txt
  src/avl.hpp
  src/document.hpp
  src/file.hpp
  src/folder.hpp
  src/hashtable.hpp
  src/main.cpp
Labels: chore

#9 Fixed format
  src/avl.hpp
  src/hashtable.hpp
Labels: chore

#8 Added headers templates
  CMakeLists.txt
  src/branch.hpp
  src/branchmanager.hpp
  src/minigit.hpp
  src/repository.hpp
  src/stash.hpp
  src/stashmanager.hpp
Labels: chore

#10 Added commit class implementation
  .gitignore
  CMakeLists.txt
  src/branch.hpp
  src/change.hpp
  src/commit.hpp
  src/diffUtils.hpp
  src/document.hpp
  src/file.hpp
  src/folder.hpp
  src/hashgen.hpp
  src/main.cpp
  src/repository.hpp
  src/stash.hpp
  src/user.hpp
  vcpkg.json
Labels: feature

#11 Added help method
  src/minigit.hpp
Labels: feature

#12 Added argument parsing
  CMakeLists.txt
  src/change.hpp
  src/commit.hpp
  src/document.hpp
  src/hashtable.hpp
  src/main.cpp
  src/minigit.hpp
  src/repository.hpp
  src/repositoryfinder.hpp
  vcpkg.json
Labels: feature
